//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Staging-Roko-Pgsql'
        USER = 'staging_user_cascade'
        PASSWORD = credentials('srvc_STAGING_pass')

    }
    stages {
        stage('Run CIF') { 
            steps {
                bat '''
                set PGPASSWORD=%PASSWORD%
                "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d staging_servicing_core -U %USER% ^
                -c "SELECT * FROM config;"
                '''
                        }
                }
           
        
        stage('Upload CIF') { 
            steps {
                bat '''
                    PAExec \\VM-ROKO-APPSERVER cmd /c "cd C:\CascadeFinancials\PGSQL\CIFFilesUploadPaymentUS\ & CIF-FilesUploadPaymentUS.exe" "
                '''
            }
        }
    }
    
}