//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Prod-Roko-Pgsql'
        USER = 'user_cascade'
        PASSWORD = credentials('srvc_PROD_pass')

    }
    stages {
        stage('Run CIF') {

                stage('Run CIF') { 
                    steps {
                        bat '''
                            set PGPASSWORD=%PASSWORD%
                            "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                            -c "SELECT * FROM config;"
                        '''
                        }
                }
            
        
                stage('Collection_Daily') { 
                    steps {
                        bat '''
                            PAExec \\STAGING-ROKO-APPSERVER cmd /c "cd C:\temp & dir & systeminfo "
                            '''
                    }
                }
            
        }
    }
}