//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"


pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Prod-Roko-Pgsql'
        USER = 'user_cascade'
        PASSWORD = credentials('srvc_PROD_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\PROD_conf.groovy'

    }
    stages {
        stage('Run DailyCollections') { 
            steps {
                bat '''
                set PGPASSWORD=%PASSWORD%
                "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                -c "SELECT five9.fn_CAS_Five9_Populate59();"
                '''
                        }
                }
           
        
        stage('Send duration to config file'){
            steps {
                script{
                    env.FIVE_NINE = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %FIVE_NINE%
                    echo env.FIVE_NINE="%FIVE_NINE%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }
    
}