//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com,sk@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Prod-Roko-Pgsql'
        USER = 'user_cascade'
        PASSWORD = credentials('srvc_PROD_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\PROD_conf.groovy'

    }
    stages {
        stage('Run reports') { 
            parallel {
                stage("REP_237"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.REP_237_BankruptcyDailyReport_Automation();"
                        '''
                    }
                }

                stage("CommentsHistory"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_CommentsHistory();"
                        '''
                    }
                }

                stage("CRWDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_CRWDaily()"
                        '''
                    }
                }

                stage("REP_246"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.REP_246_ForeclosureDailyReport_Automation();"
                        '''
                    }
                }

                stage("LMDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_LMDaily();"
                        '''
                    }
                }

                stage("LMPayPlans"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_LMPayPlans();"
                        '''
                    }
                }

                stage("LMSInsightDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_LMSInsightDaily();"
                        '''
                    }
                }

                stage("LMSOpsDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_LMSOpsDaily();"
                        '''
                    }
                }

                stage("LossMitMilestones"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_LossMitMilestones();"
                        '''
                    }
                }

                stage("PaymentPlanDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_PaymentPlanDaily();"
                        '''
                    }
                }


                stage("REODaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_REODaily();"
                        '''
                    }
                }

                stage("StandardDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_StandardDaily();"
                        '''
                    }
                }

                stage("SupplementalDaily"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_SupplementalDaily();"
                        '''
                    }
                }

                stage("TransactionHistory"){
                    steps {
                        bat '''
                        set PGPASSWORD=%PASSWORD%
                        "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                        -c "SELECT firstkey.Report_FirstKeyServicer_TransactionHistory();"
                        '''
                    }
                }

            }
        }

        stage('Run Python Script') { 
            steps {
                bat '''
                    PAExec \\\\PROD-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PGSQL\\FirstKeyDailyFileUploader\\ & python FirstKeyDailyFileUploader.py"
                '''
            }
        }

        stage('Send duration to config file'){
            steps {
                script{
                    env.FIRSTKEY_REPORTS = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %FIRSTKEY_REPORTS%
                    echo env.FIRSTKEY_REPORTS="%FIRSTKEY_REPORTS%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }

    post {
        success {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: FirstKey",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>FirstKey</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #99cc00; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> You can finde details on this </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
        }
         failure {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: FirstKey",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>FirstKey &nbsp;</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #ff0000; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> This build failed, please check what is wrong!  </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
                    
        }
    } 

}