pipeline {
    agent { label 'vm-roko-jenkins' }
    stages {
        stage('Check files') { 
            steps {
                bat 'python scripts\check_files.py'
                // 
            }
        }
        stage('Copy file for MSSQL folder') { 
            steps {
                bat 'echo Step2'
                // 
            }
        }
        stage('Rename and delete files ') { 
            steps {
                bat 'echo Step3'
                // 
            }
        }
        stage('Run IFP_proces_cusctom ') { 
            steps {
                bat 'echo Step4'
                // 
            }
        }
        stage('Generate and send report') { 
            steps {
                bat 'echo Step5'
                // 
            }
        }
    }
}