pipeline {
    agent { label 'vm-roko-jenkins' }
    stages {
        stage('Check files') { 
            steps {
                bat 'python %cd%\\ifp\\scripts\\check_files.py'
                // 
            }
        }
        stage('Copy file for MSSQL folder') { 
            steps {
                bat '''
                %cd%\\ifp\\scripts\\copy_files_for_pos.cmd \
                \\\\vm-roko-appserver\\temp\\jenkins\\source \
                \\\\vm-roko-appserver\\temp\\jenkins\\MSSQL
                '''
                // Use additional / (slash) for use on WINDOWS slave
                //first parameter is SOURCE folder
                // second - is DESTINATION folder
            }
        }
        stage('Run IFP_proces_cusctom ') { 
            steps {
                bat 'echo Step4'
                // 
            }
        }
        stage('Generate and send report') { 
            steps {
                bat 'echo Step5'
                // 
            }
        }
    }
}