//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"


pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Staging-Roko-Postgres'
        USER = 'staging_user_cascade'
        PASSWORD = credentials('srvc_STAGING_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\STAGING_conf.groovy'

    }
    stages {
        stage('Run DailyCollections') { 
            steps {
                bat '''
                set PGPASSWORD=%PASSWORD%
                "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d staging_servicing_core -U %USER% ^
                -c "SELECT rpt.Servicing_Collection_Daily_sp (NULL, 0);"
                '''
                        }
                }
           
        
        stage('Send duration to config file'){
            steps {
                script{
                    env.DAILY_COLLECTIONS = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %DAILY_COLLECTIONS%
                    echo env.DAILY_COLLECTIONS="%DAILY_COLLECTIONS%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }
    
}