pipeline {
    agent { label 'vm-roko-jenkins' }
    stages {
        stage('Check files') { 
            steps {
                bat '''
                    python %cd%\\ifp\\DEV\\FileCheck.py
                '''
///                script{
///                    env.CHECK_FILE_END = "${currentBuild.durationString.split(" ")[0..1]}"
                }
                // 
        }
        
        stage('Copy file to MSSQL folder') { 
            steps {
                bat '''
                    ::%cd%\\ifp\\DEV\\copy_files_for_pos.cmd \
                    ::\\\\vm-roko-appserver\\CascadeFinancials\\Cobol\\CobolTempDirectory\\MSSQL \
                    ::\\\\vm-roko-appserver\\temp\\jenkins\\MSSQL
                '''
                // Use additional / (slash) for use on WINDOWS slave
                //first parameter is SOURCE folder
                // second - is DESTINATION folder
            }
        }
        stage('Run IFP proces MSSQL ') { 
            steps {
                bat '''
                    ::python %cd%\\ifp\\DEV\\mssql\\RunIFP_mssql.py
                '''
                // 
            }
        }
        stage('Generate and send report') { 
            steps {
                bat '''
                    python %cd%\\ifp\\generate_report_IFP.py
                '''
                // 
            }
        }
    }
    post {
        success {
            mail to: 'kirill.sergeev@rokolabs.com',
            subject: "Status of pipeline: ${currentBuild.fullDisplayName}",
            body: """
                <p><span style="color: #003366;"><strong>${currentBuild.projectName}&nbsp;</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;">Build:&nbsp;<strong>${currentBuild.projectName}&nbsp;</strong></span></p>
                <div><span style="color: #003366;">Number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #99cc00; color: #003366;">${currentBuild.result}</span></h3>
                </div>
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> You can finde details on this </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>,
                 mimeType: 'text/html'
            """
            
        }
    }
    
}