pipeline {
    agent { label 'vm-roko-jenkins' }
    stages {
        stage('Check files') { 
            steps {
                def CHECK_FILE_START = bat(script: "%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%", returnStdout: true)
                bat '''
                #set CHECK_FILE_START=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                python %cd%\\ifp\\DEV\\FileCheck.py
                set CHECK_FILE_END=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                '''
                // 
            }
        }
        stage('Copy file to MSSQL folder') { 
            steps {
                bat '''
                set COPY_FILE_START=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                %cd%\\ifp\\DEV\\copy_files_for_pos.cmd \
               \\\\vm-roko-appserver\\CascadeFinancials\\Cobol\\CobolTempDirectory\\MSSQL \
                \\\\vm-roko-appserver\\temp\\jenkins\\MSSQL
                set COPY_FILE_END=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                '''
                // Use additional / (slash) for use on WINDOWS slave
                //first parameter is SOURCE folder
                // second - is DESTINATION folder
            }
        }
        stage('Run IFP proces MSSQL ') { 
            steps {
                bat '''
                set IFP_PROCESS_START=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                #python %cd%\\ifp\\DEV\\mssql\\RunIFP_mssql.py
                set IFP_PROCESS_END=%TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2%
                '''
                // 
            }
        }
        stage('Generate and send report') { 
            steps {
                echo "$CHECK_FILE_START%"
                bat '''
                python %cd%\\ifp\\generate_report_IFP.py
                                '''
                // 
            }
        }
    }
}