//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Staging-Roko-Postgres'
        USER = 'staging_user_cascade'
        PASSWORD = credentials('srvc_STAGING_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\STAGING_conf.groovy'

    }

    stages{
        stage('Run Selenium Python Script') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PaymentusProcess\\ & python PaymentusProcess.py"
                '''
            }
        }

        stage('Run PaymentusSinglePayment ') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PaymentusProcess\\ & PaymentusSinglePayments.cmd"
                '''
            }
        }

        stage('Run PaymentusRecurringPayments ') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PaymentusProcess\\ & PaymentusRecurringPayments.cmd"
                '''
            }
        }

        stage('Send duration to config file'){
            steps {
                script{
                    env.PAYMENTUS_REPORTS = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %PAYMENTUS_REPORTS%
                    echo env.PAYMENTUS_REPORTS="%PAYMENTUS_REPORTS%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }

}
    