//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com,sk@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Prod-Roko-Pgsql'
        USER = 'user_cascade'
        PASSWORD = credentials('srvc_PROD_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\PROD_conf.groovy'

    }
    stages {
        stage('Run CIF') { 
            steps {
                bat '''
                set PGPASSWORD=%PASSWORD%
                "C:\\Program Files\\PostgreSQL\\12\\bin\\psql.exe" -h %HOST_NAME% -p 5432 -d servicing_core -U %USER% ^
                -c "SELECT cif.sp_CIF_FileCreation ();"
                '''
                        }
                }
           
        
        stage('Upload CIF') { 
            steps {
                bat '''
                    PAExec \\\\PROD-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PGSQL\\CIFFilesUploadPaymentUS\\ & CIF-FilesUploadPaymentUS.exe"
                '''
            }
        }
       
        stage('Send duration to config file'){
            steps {
                script{
                    env.CIF_REPORTS = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %CIF_REPORTS%
                    echo env.CIF_REPORTS="%CIF_REPORTS%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }

    post {
        success {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: CIF",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>CIF Run and Upload</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #99cc00; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> You can finde details on this </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
        }
         failure {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: CIF Run and Upload failed",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>CIF Run and Upload &nbsp;</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #ff0000; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> This build failed, please check what is wrong!  </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
                    
        }
    }    
    
}