//Set variables
def MAIL_TO = "kirill.sergeev@rokolabs.com"

pipeline {
    agent { label 'vm-roko-jenkins' }
    environment {
        HOST_NAME = 'Staging-Roko-Postgres'
        DB_NAME = "staging_servicing_core"
        USER = 'staging_user_cascade'
        PASSWORD = credentials('srvc_STAGING_pass')
        CONFIG_FILE = '\\\\vm-roko-jenkins\\JENKINS\\STAGING_conf.groovy'
        DATA_PATH = 'D:\\FilesToTransfer\\Paymentus\\output'
        PAY_PASSWORD = credentials('paymentus_pass')

    }

    stages{
        stage('Run Selenium Python Script') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PGSQL\\PaymentusProcess\\ & python PaymentusProcess.py"
                '''
            }
        }

        stage('Run PaymentusSinglePayment ') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PGSQL\\PaymentusProcess\\ & PaymentusSinglePayments.cmd %DATA_PATH% %HOST_NAME% %DB_NAME% %USER% %PASSWORD%"
                '''
            }
        }

        stage('Run PaymentusRecurringPayments ') { 
            steps {
                bat '''
                    PAExec \\\\STAGING-ROKO-APPSERVER cmd /c "D: & cd D:\\CascadeFinancials\\PGSQL\\PaymentusProcess\\ & PaymentusRecurringPayments.cmd %DATA_PATH% %HOST_NAME% %DB_NAME% %USER% %PASSWORD%   "
                '''
            }
        }

        stage('Send duration to config file'){
            steps {
                script{
                    env.PAYMENTUS_REPORTS = "${currentBuild.durationString.minus(' and counting')}"
                }
                bat '''
                    echo %PAYMENTUS_REPORTS%
                    echo env.PAYMENTUS_REPORTS="%PAYMENTUS_REPORTS%" >> %CONFIG_FILE%
                '''
                // 
            }
        }

    }

    post {
        success {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: Paymentus STAGING",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>Paymentus STAGING</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #99cc00; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> You can finde details on this </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
        }
         failure {
            mail to: "${MAIL_TO}",
            subject: "Status of pipeline: Paymentus failed STAGING",
            body: """
                <html>
                <p><span style="color: #003366;"><strong>Paymentus STAGING &nbsp;</strong></span></p>
                <p><span style="color: #003366;">===========================================</span><br /><span style="color: #003366;"></span></p>
                <div><span style="color: #003366;">Build number:&nbsp;<strong>${currentBuild.number}</strong></span></div>
                <p><span style="color: #003366;">Has result:</span></p>
                <div>
                <h3><span style="background-color: #ff0000; color: #003366;">${currentBuild.result}</span></h3>
                </div><br />
                <p><span style="color: #003366;">Duration:&nbsp;<strong>${currentBuild.durationString}&nbsp;</strong></span><br />
                <span style="color: #003366;"> This build failed, please check what is wrong!  </span><br /><span style="color: #003366;">link: ${env.BUILD_URL}</span>
                <br /><span style="color: #003366;">===========================================</span></p>
                </html>
                 """,
            mimeType: 'text/html'
                    
        }
    }

}

    